# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cafe Print' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'NotificationBannerSwift', '1.6.3'
  pod 'MarqueeLabel/Swift', '3.1.6'
  pod 'SideMenuSwift' ,'2.0.2'
  pod 'BonsaiController'
  pod 'AlamofireImage', '~> 3.5'
  pod 'IQKeyboardManagerSwift'
  pod 'RxSwift'
  pod 'ReactiveCocoa', '~> 10.1'
  pod 'RxTheme'
  pod 'Firebase/Core'
  pod 'FirebaseMessaging'
  pod 'Firebase/Auth'

  # Pods for Cafe Print

  target 'Cafe PrintTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Cafe PrintUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
